# Generated by Django 6.0.7 on 2026-08-10 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0003_alter_categoria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.PositiveSmallIntegerField(choices=[(1, 'Mesa 1'), (2, 'Mesa 2'), (3, 'Mesa 3'), (4, 'Mesa 4'), (5, 'Mesa 5'), (6, 'Mesa 6'), (7, 'Mesa 7'), (8, 'Mesa 8'), (9, 'Mesa 9'), (10, 'Mesa 10'), (11, 'Mesa 11'), (12, 'Mesa 12'), (13, 'Mesa 13'), (14, 'Mesa 14'), (15, 'Mesa 15'), (16, 'Mesa 16'), (17, 'Mesa 17'), (18, 'Mesa 18'), (19, 'Mesa 19'), (20, 'Mesa 20'), (21, 'Mesa 21'), (22, 'Mesa 22'), (23, 'Mesa 23'), (24, 'Mesa 24'), (25, 'Mesa 25'), (26, 'Mesa 26'), (27, 'Mesa 27')])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
        ),
    ]
