# Generated by Django 6.0.7 on 2026-07-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_produto_preco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
